DOXIATOOLS-64_full_log

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -26,11 +26,11 @@ jobs:
   
       - name: Test with Maven 
         run: | 
-              for i in {1..100}; do mvn test -Dtest=org.apache.maven.doxia.book.services.renderer.docbook.DocBookBookSinkTest -Drat.skip -fae>>test_log.txt; done
-              echo "Maven tests completed." 
+              for i in {1..100}; do mvn test -Dtest=org.apache.maven.doxia.book.services.renderer.docbook.DocBookBookSinkTest -Drat.skip -fae>>test_log_DOXIATOOLS-64.txt || echo "Test iteration $i failed">>test_log_DOXIATOOLS-64.txt; done
+              
       - name: Upload Test Log 
         if: always() 
         uses: actions/upload-artifact@v2 
         with: 
-          name: test_log 
-          path: test_log.txt
+          name: test_log_DOXIATOOLS-64
+          path: test_log_DOXIATOOLS-64.txt
